singleNode: true
replicas: 1

image:
  tag: "2.19.1"

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

service:
  type: NodePort
  nodePort: 30920

extraEnvs:
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "true"
  - name: DISABLE_SECURITY_PLUGIN
    value: "true"

config:
  opensearch.yml: |
    cluster.name: opensearch-cluster
    network.host: 0.0.0.0
    discovery.type: single-node

persistence:
  enabled: true
  size: 10Gi

sysctlInit:
  enabled: true
